### ISSUE TITLE
First Level Design

### ISSUE THREAD

**Issue by aespablo** [envybros/project-g#14]

**Comment by 6to9** [comment]
이거... 블렌더 한 번 거치고 가야할 것 같아요.
`.glb`파일로 묶어야 제대로 열릴 것 같은데... ㅜㅠ

**Comment by 6to9** [comment]
<img width="1058" alt="image" src="https://github.com/user-attachments/assets/dfa3cc04-cc93-48cf-aec0-a7c2f27b696d">

**Comment by pulppixel** [comment]
> <img alt="image" width="1058" src="https://private-user-images.githubusercontent.com/171216337/363611915-dfa3cc04-cc93-48cf-aec0-a7c2f27b696d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzY0NjMsIm5iZiI6MTcyNTQzNjE2MywicGF0aCI6Ii8xNzEyMTYzMzcvMzYzNjExOTE1LWRmYTNjYzA0LWNjOTMtNDhjZi1hZWMwLWE3YzJmMjdiNjk2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQwNzQ5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTgzMDRlODViYWMzODhkMzEwYTU1MDg2MmVjMThhYjExYmY5MDZhMThjMGIyNzU1YzVjNmNhNGI1NWZhMzZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4XYRXf8uCI-oeGsyhlBxU8sCe9SBAB5r_TamCaWs6yA">

와.. 이건 무조건 glb 파일로 가야겄네.. 애니메이션 적용 좀 쉽게 하는 법 찾았다고 그러드만

레벨 디자인 쪽 많이 멋졌으면 좋겠다잉

Vertical Fog도 엔진에서 지원한다며.. 참 좋은 엔진이여
